// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cSharpPro.Datacontext;

namespace cSharpPro.Migrations
{
    [DbContext(typeof(KioskDbcontext))]
    partial class KioskDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cSharpPro.Models.bagsDB", b =>
                {
                    b.Property<string>("NO")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<string>("picked");

                    b.Property<string>("price");

                    b.HasKey("NO");

                    b.ToTable("bagdbs");
                });
#pragma warning restore 612, 618
        }
    }
}
